title: 'UCSF HPC: TIPCC'
theme: jekyll-theme-minimal

cluster:
  name: "TIPCC"

login:
  name: "cclc01"
  hostname: "cclc01.som.ucsf.edu"
  ip: "169.230.134.141"

devel:
  name: "n6"
  hostname: "n6"
  ip: "10.54.50.6"

interactive:
  name: "n6"
  hostname: "n6"
  ip: "10.54.50.6"

transfer:
  name: "cclc01"
  hostname: "cclc01.som.ucsf.edu"
  ip: "169.230.134.141"

specs:
  nodes: 18
  physical_cores: 724
  communal_nodes: 7
  communal_cores: 84
  gpu_nodes: 0
  gpus: 0
  communal_gpu_nodes: 0
  communal_gpus: 0
  last_node: n34
